---
title: "Lab 09 - Grading the professor, Pt. 1"
author: "Steph Bossert"
date: "5 april 2021"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(tidymodels)
library(openintro)
library(ggplot2)
?evals
view(evals)
```

### Exercise 1
Positively skewed, mean = 4.18, max = 5, 
Students tend to give positive evaluations for their professors as the data is positively skewed.


```{r score}
evals2 <- ggplot(evals, aes(x = score))
evals2 + geom_histogram(bins = 30, color = "white", fill = "blue") +
  geom_vline(aes(xintercept = mean(score)), 
             linetype = "dashed", size = 0.6)
summary(evals$score)

```

### Exercise 2
There is a direct, positive relationship between a professor's beuty score and their evalution score... interesting. 
```{r score and bty_avg}
ggplot(evals, aes(x=score, y=bty_avg)) + 
  geom_point(shape=18, color="blue")+
  geom_smooth(method=lm, se=FALSE, linetype="solid",
             color="red")

```


